---
- name: Scale or descale a VM pool based on a pool max and min size
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # These two can come from an event in EDA
    # scale_direction: 'up'
    # scale_direction: 'down'
    min_vms: 1
    max_vms: 5

    appname: dummyapp

    # By convention vm names are
    # vm-app-## (starting at "01")

    # Creation requires a namespace
    # namespace: "{{ appname }}"
      
  tasks:
    # Find out how many VMS are up
    - name: Get all existing VirtualMachines in the {{ appname }} pool
      redhat.openshift_virtualization.kubevirt_vm_info:
        namespace: "{{ namespace | default(omit) }}"
        label_selectors:
          # always select by an appname
          - app = {{ appname }}
      register: vm_information
      tags:
        - evaluation

    - name: Get list of all vms, sorted
      ansible.builtin.set_fact:
        #vm_list: "vm_information.resources[].name"
        vm_list: "vm_information.resources | selectattr('name') | sort"
      tags:
        - evaluation
      

    - name: Find out if VM creation or removal is needed based on pool size
      ansible.builtin.set_fact:
        action_needed: "{{ true if (vm_list | length > min_vms and vm_list | length < max_vms ) else false }}" 
      tags:
        - evaluation
      
    - name: Create a new vm my-vm{{ len(vm_list) + 1 }}
      redhat.openshift_virtualization.kubevirt_vm:
        state: present
        name: vm-{{ appname }}{{ '%02d'%(len(vm_list) + 1) }}
        namespace: dap
        labels:
          - 'app: {{ appname }}'
        wait: true
        run_strategy: Always
        data_volume_templates: "{{ lookup('template', 'templates/datavolume-' ~ appname ~ '.yml') }}"
        # spec: templates/vmspec-{{ appname }}.yml
        spec: "{{ lookup('template', 'templates/vmspec-' ~ appname ~ '.yml') }}"
      when: > 
        (action_needed and scale_direction =='up') or
        (len(vm_list)<= min_vms and scale_direction=='up')

                
    - name: Delete the latest VM by name
      when: action_needed and scale_direction =='down'
      redhat.openshift_virtualization.kubevirt_vm:
        state: absent
        # Delete the last existing machine
        name: "{{ vm_list[-1] }}"
        namespace: dap
        wait: true


      